# A skeleton sysroot specification file.

[OpenSSL]
version = "3.1.1"
disabled_targets =["ios"]

[Python]
version = "3.11.3"

[PyQt]
version = "6.5.1"

[PyQt.android]
disabled_features = ["PyQt_Desktop_OpenGL", "PyQt_Printer"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtAndroidExtras"]

[PyQt.ios]
disabled_features = ["PyQt_Desktop_OpenGL", "PyQt_MacOSXOnly",
        "PyQt_MacCocoaViewContainer", "PyQt_Printer", "PyQt_Process",
        "PyQt_NotBootstrapped"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtMacExtras"]

[PyQt.linux]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtX11Extras"]

[PyQt.macos]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtMacExtras"]

[PyQt.win]
disabled_features = ["PyQt_Desktop_OpenGL"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtWinExtras"]

[QScintilla]
version = "2.13.2"

[Qt]
version = "6.5.1"
edition = "opensource"
configure_options = ["-opengl", "desktop", "-qt-pcre"]
skip = ["qtactiveqt", "qtconnectivity", "qtdoc", "qtgamepad", "qtlocation",
        "qtmultimedia", "qtnetworkauth", "qtquickcontrols",
        "qtquickcontrols2", "qtremoteobjects", "qtscript", "qtscxml",
        "qtsensors", "qtserialbus", "qtserialport", "qtspeech", "qtsvg",
        "qttools", "qttranslations", "qtwayland", "qtwebchannel",
        "qtwebengine", "qtwebsockets", "qtwebview", "qtxmlpatterns"]

[Qt.android]
install_from_source = false
ssl = "openssl-linked"

[Qt.ios]
install_from_source = false
ssl = "securetransport"

[Qt.linux]
ssl = "openssl-runtime"

[Qt.macos]
ssl = "openssl-linked"

[Qt.win]
ssl = "openssl-linked"
static_msvc_runtime = true

[SIP]
abi_major_version = 12
module_name = "PyQt6.sip"

[zlib]
install_from_source = false

[zlib.win]
version = "1.2.12"
install_from_source = true
static_msvc_runtime = true
